- name: Imports influxdb apt key
  apt_key: 
    url: https://repos.influxdata.com/influxdb.key
    state: present

- name: Adds influxdb repository
  apt_repository:
    repo: "deb https://repos.influxdata.com/{{ ansible_lsb.id | lower }} {{ ansible_lsb.codename }} stable"
    state: present
    update_cache: yes

- name: Installs influxdb
  apt:
    pkg: influxdb
    state: present
  notify:
    - Start influxdb

- name: Adds influxdb configuration
  template:
    src: influxdb.conf.j2
    dest: /etc/influxdb/influxdb.conf
    mode: 0640
    owner: influxdb
    group: root
  notify:
    - Restart influxdb

- name: Creates influxdb admin user
  influxdb_user:
    user_name: "{{ influxdb_admin_user }}"
    user_password: "{{ influxdb_admin_password }}"
    login_username: "{{ influxdb_admin_user }}"
    login_password: "{{ influxdb_admin_password }}"
    admin: yes
  when: influxdb_admin_user is defined and influxdb_admin_password is defined
